# -*- coding: utf-8 -*-
"""musify_p1r.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-s18nfnIRIjKFV3x2xp7KOCVMm9bbmAY

# 🎧 **Laporan Proyek Machine Learning - Krismono Sadi**

## 📌 Sistem Rekomendasi Lagu Spotify

## Dataset Web API: [Spotify Developer API](https://developer.spotify.com/documentation/web-api?directory=true)

## 📖 **Project Overview**

## 🧠 **Business Understanding**

### 🎯 **Problem Statements**

* Bagaimana merekomendasikan lagu relevan berdasarkan riwayat pemutaran pengguna?
* Bagaimana mengevaluasi performa sistem rekomendasi yang dikembangkan?

### ✅ **Goals**

* Mengembangkan sistem rekomendasi **Top-N Lagu**.
* Mengukur performa model dengan metrik seperti **RMSE** dan **Precision\@K**.

### 💡 **Solution Approach**

* **Collaborative Filtering**: Menggunakan *Matrix Factorization (SVD)* untuk menangkap hubungan tersembunyi antara user dan lagu.
* **Content-Based Filtering**: Memanfaatkan fitur lagu (genre, durasi, popularitas) untuk menyarankan lagu serupa dengan preferensi pengguna.

# Library
"""

# 1. Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import warnings
warnings.filterwarnings('ignore')
import random

"""# Load Dataset

Kita akan meload data yang udah scrapping dari api spotify
"""

# 2. Load Dataset (asumsi file lokal sudah tersedia)
file_path = "spotify_cris_music1.csv"
df = pd.read_csv(file_path)

"""# **Data Understanding**

# Menampilkan 5 baris data pertama
"""

print("\nFirst 5 rows:")
print(df.head())

"""# Menampilkan informasi dataset seperti tipe data dan jumlah non-null per kolom

### Tabel Struktur Data

| No | Kolom         | Non-Null Count | Tipe Data |
|----|---------------|----------------|-----------|
| 0  | name          | 5624           | object    |
| 1  | artist        | 5624           | object    |
| 2  | album         | 5624           | object    |
| 3  | popularity    | 5624           | int64     |
| 4  | explicit      | 5624           | bool      |
| 5  | release_date  | 5624           | object    |
| 6  | duration_ms   | 5624           | int64     |
| 7  | preview_url   | 0              | float64   |

**Total Baris**: 5624  
**Total Kolom**: 8  
**Penggunaan Memori**: ~313.2 KB
"""

print("\nInfo:")
print(df.info())

"""# Menampilkan jumlah baris dan Kolom (data) pada dataset"""

print(f"\nJumlah data (baris): {df.shape[0]}")
print(f"Jumlah fitur (kolom): {df.shape[1]}")

"""# Mengecek jumlah data yang duplikat"""

print("\nDuplicate check:", df.duplicated().sum())

"""# Mengecek jumlah nilai kosong (null) per kolom"""

print("\nNull check:")
print(df.isnull().sum())

"""# Menyimpan jumlah baris dan kolom ke variabel"""

rows, cols = df.shape

"""# Pemeriksaan nilai kosong (missing values) secara spesifik"""

# Pemeriksaan missing value (duplikat)
print("\nMissing Values:")
print(df.isnull().sum())

"""# Menampilkan informasi jumlah data dan fitur secara lengkap"""

# Menampilkan jumlah baris dan kolom
rows, cols = df.shape
print(f"\nJumlah data: {rows} baris dan {cols} kolom")

"""# Menampilkan statistik deskriptif untuk kolom numerik seperti mean, std, min, max"""

# Statistik deskriptif untuk kolom numerik
print("\nStatistik Deskriptif:")
print(df.describe())

"""# **Univariate EDA**"""

# 4. Univariate EDA
# Menampilkan 5 lagu teratas berdasarkan popularitas
print("\nTop 5 Lagu dengan Popularitas Tertinggi:")
top5 = df[['name', 'artist', 'popularity']].sort_values(by='popularity', ascending=False).head()
print(top5.to_string(index=False))

# Visualisasi distribusi popularitas
plt.figure(figsize=(10, 6))
sns.histplot(df['popularity'], bins=25, kde=True, color='skyblue', edgecolor='black')
plt.title('Distribusi Popularitas Lagu', fontsize=14)
plt.xlabel('Popularity', fontsize=12)
plt.ylabel('Jumlah Lagu', fontsize=12)
plt.grid(axis='y', linestyle='--', linewidth=0.7)
plt.tight_layout()
plt.show()

# Statistik deskriptif tambahan untuk popularitas
print("\nStatistik Deskriptif untuk Popularitas:")
print(df['popularity'].describe())

"""# **Data Preparation**

# **5. Preprocessing**
"""

# 5. Preprocessing
df.drop_duplicates(inplace=True)
df.dropna(subset=['name', 'artist', 'popularity'], inplace=True)

"""# **6. Data Preparation**"""

# 6. Data Preparation
np.random.seed(42)

# Pastikan user_id 1 sampai 200 pasti ada, assign secara berulang
user_ids = np.arange(1, 201)
repeats = len(df) // len(user_ids) + 1
user_id_full = np.tile(user_ids, repeats)[:len(df)]
df['user_id'] = user_id_full

# Encoding songs dan users
df['song_id'] = df['name'].astype('category').cat.codes
df['user_enc'] = df['user_id'].astype('category').cat.codes

# Normalisasi rating dari popularity
df['rating'] = df['popularity'] / 100

# Mappings
user_to_id = dict(zip(df['user_id'], df['user_enc']))
song_to_id = dict(zip(df['name'], df['song_id']))
id_to_song = {v: k for k, v in song_to_id.items()}

num_users = df['user_enc'].nunique()
num_songs = df['song_id'].nunique()
EMBEDDING_SIZE = 50

"""# **Model Development - Collaborative Filtering with deeper architecture + dropout**

Penggunaan pendekatan Collaborative Filtering dengan arsitektur yang lebih dalam (deeper architecture) dan dropout dalam pengembangan model rekomendasi memiliki tujuan untuk meningkatkan kemampuan generalisasi model, mengurangi overfitting, dan menangkap pola interaksi yang lebih kompleks antara pengguna dan item (lagu).

1. Collaborative Filtering (CF) Dasar
Collaborative Filtering adalah pendekatan populer dalam sistem rekomendasi, yang bekerja dengan mengandalkan interaksi historis antara user dan item (tanpa melihat isi/item features).

Matrix Factorization (MF) adalah bentuk dasar dari CF: memetakan user dan item ke latent space (biasanya vektor berdimensi rendah) untuk memprediksi preferensi.

Namun, MF klasik terbatas secara representatif dan bisa terlalu sederhana untuk menangkap hubungan non-linear yang kompleks.

2. Deeper Architecture (Neural CF / Deep MF)
Dengan menambahkan arsitektur neural network yang lebih dalam, kita:

✅ Menangkap hubungan non-linear antara user dan item
✅ Memungkinkan pembelajaran representasi kompleks untuk user dan lagu
✅ Lebih fleksibel terhadap fitur tambahan jika ingin di-extend (genre, audio feature, dll.)

Contoh: alih-alih hanya punya user_embedding dan item_embedding yang dikalikan, kita bisa menggabungkannya dan melewatkannya ke beberapa dense layer.

3. Mengapa Perlu Dropout?
Dropout adalah teknik regularisasi yang secara acak menonaktifkan sejumlah neuron selama training.

Manfaat:

⚠️ Mencegah overfitting terhadap data training
⚙️ Membuat model lebih robust dan general saat prediksi ke data baru
📉 Menurunkan risiko "memorizing" data interaksi user yang terbatas
"""

# 7. Model Development - Collaborative Filtering with deeper architecture + dropout
class RecommenderNet(keras.Model):
    def __init__(self, num_users, num_items, embedding_size, **kwargs):
        super(RecommenderNet, self).__init__(**kwargs)
        self.user_embedding = layers.Embedding(num_users, embedding_size, embeddings_initializer='he_normal', embeddings_regularizer=keras.regularizers.l2(1e-6))
        self.user_bias = layers.Embedding(num_users, 1)
        self.item_embedding = layers.Embedding(num_items, embedding_size, embeddings_initializer='he_normal', embeddings_regularizer=keras.regularizers.l2(1e-6))
        self.item_bias = layers.Embedding(num_items, 1)

        self.dot = layers.Dot(axes=1)
        self.dense1 = layers.Dense(128, activation='relu')
        self.dropout1 = layers.Dropout(0.3)
        self.dense2 = layers.Dense(64, activation='relu')
        self.dropout2 = layers.Dropout(0.3)
        self.out = layers.Dense(1, activation='sigmoid')

    def call(self, inputs):
        user_vector = self.user_embedding(inputs[:, 0])
        item_vector = self.item_embedding(inputs[:, 1])

        user_bias = self.user_bias(inputs[:, 0])
        item_bias = self.item_bias(inputs[:, 1])

        x = tf.concat([user_vector, item_vector], axis=1)
        x = self.dense1(x)
        x = self.dropout1(x)
        x = self.dense2(x)
        x = self.dropout2(x)
        x = self.out(x)

        # Add biases
        x = x + user_bias + item_bias
        return tf.squeeze(x, axis=1)

"""# Prepare training data

Tujuan tahap ini adalah untuk:

Meng-encode user_id dan song_id ke integer.

Menyusun dataset sebagai pasangan (user, song) → rating (target).

Melakukan train-test split agar kita bisa menguji model setelah pelatihan.
"""

# 8. Prepare training data
train_data = df[['user_enc', 'song_id', 'rating']]
x = train_data[['user_enc', 'song_id']].values
y = train_data['rating'].values

"""# Compile and Train Model

Setelah model dibuat (misalnya model embedding untuk user dan lagu, lalu digabungkan dan diberi dense layer dengan dropout), kita perlu:

Compile model: Tentukan fungsi loss, optimizer, dan metrik evaluasi.

Train model: Latih model dengan data training, validasi menggunakan data testing untuk memonitor performa.
"""

# 9. Compile and Train Model
model = RecommenderNet(num_users, num_songs, EMBEDDING_SIZE)
model.compile(
    loss=tf.keras.losses.MeanSquaredError(),
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    metrics=[tf.keras.metrics.RootMeanSquaredError()]
)

history = model.fit(x, y, batch_size=64, epochs=20, verbose=1, validation_split=0.1)

"""# Evaluasi model di data training

Evaluasi model dilakukan untuk mengetahui seberapa baik model mempelajari pola dari data training. Biasanya menggunakan metrik seperti:

Root Mean Squared Error (RMSE): Mengukur selisih antara rating asli dan prediksi. Semakin kecil nilai RMSE, semakin baik.

Loss: Nilai error fungsi loss saat training.

Selain angka metrik, kamu juga bisa buat visualisasi seperti plot loss dan RMSE selama training untuk melihat apakah model mengalami overfitting atau underfitting.
"""

# 1. Evaluasi model di data training
loss, rmse = model.evaluate(x, y, verbose=0)
accuracy = (1 - rmse) * 100  # Konversi ke persentase

print(f"\nModel Evaluation:")
print(f"Loss: {loss:.4f}")
print(f"RMSE: {rmse:.4f}")
print(f"Akurasi (perkiraan): {accuracy:.2f}%")

if accuracy >= 90:
    print("Model Anda udah bagus banget!")
elif accuracy >= 80:
    print("Model lumayan")
else:
    print("Model perlu ditingkatkan")

# 2. Visualisasi grafik Loss dan RMSE selama training
plt.figure(figsize=(12,5))

# Plot Loss
plt.subplot(1, 2, 1)
plt.plot(history.history['loss'], label='Training Loss')
plt.title('Training Loss per Epoch')
plt.xlabel('Epoch')
plt.ylabel('Loss (MSE)')
plt.legend()

# Plot RMSE
plt.subplot(1, 2, 2)
plt.plot(history.history['root_mean_squared_error'], label='Training RMSE', color='orange')
plt.title('Training RMSE per Epoch')
plt.xlabel('Epoch')
plt.ylabel('RMSE')
plt.legend()

plt.tight_layout()
plt.show()

"""# Recommendation Function

Fungsi rekomendasi ini bertugas memberikan daftar lagu yang direkomendasikan untuk setiap pengguna berdasarkan model yang sudah dilatih.

Cara kerjanya:

Ambil ID pengguna.

Prediksi skor preferensi untuk semua lagu yang belum pernah didengarkan pengguna tersebut.

Urutkan lagu berdasarkan skor tertinggi.

Kembalikan daftar lagu rekomendasi Top-N.
"""

# 11. Recommendation Function
def recommend_songs(user_id, top_n=5):
    user_enc = user_to_id.get(user_id)
    if user_enc is None:
        return ["User tidak ditemukan."]

    seen_songs = df[df['user_enc'] == user_enc]['song_id'].tolist()
    all_songs = np.array(list(song_to_id.values()))
    unseen_songs = np.setdiff1d(all_songs, seen_songs)

    user_array = np.array([user_enc] * len(unseen_songs))
    pred_input = np.vstack((user_array, unseen_songs)).T
    predictions = model.predict(pred_input, verbose=0).flatten()
    top_indices = predictions.argsort()[-top_n:][::-1]
    recommended_ids = unseen_songs[top_indices]
    return [id_to_song[i] for i in recommended_ids]

"""# Statistical Recommendations

Bagian ini menyajikan statistik rekomendasi berdasarkan data lagu yang ada, tanpa memerlukan model prediksi. Statistik ini berguna untuk memberikan insight awal seperti:

Lagu-lagu paling populer berdasarkan popularitas Spotify

Lagu dengan durasi terpanjang

Lagu yang paling sering diputar (top trending)

Lagu dengan konten eksplisit terbanyak

Tujuan Statistik Rekomendasi
Memberikan rekomendasi default yang umum disukai pengguna baru tanpa riwayat.

Melengkapi sistem rekomendasi berbasis model dengan insight data yang lebih sederhana.

Membantu memvalidasi distribusi data dan pola dalam dataset.
"""

# 12. Statistical Recommendations
def top_trending_songs(df, top_n=10):
    df_copy = df.drop_duplicates(subset=['name'])
    df_copy['release_date'] = pd.to_datetime(df_copy['release_date'], errors='coerce')
    trending = df_copy.sort_values(by='release_date', ascending=False)
    return trending[['name', 'artist', 'release_date']].head(top_n)

def top_popular_songs(df, top_n=10):
    popular = df.drop_duplicates(subset=['name']).sort_values(by='popularity', ascending=False)
    return popular[['name', 'artist', 'popularity']].head(top_n)

def top_explicit_songs(df, top_n=10):
    explicit = df[df['explicit'] == True].drop_duplicates(subset=['name']).sort_values(by='popularity', ascending=False)
    return explicit[['name', 'artist', 'popularity']].head(top_n)

def top_longest_duration(df, top_n=10):
    longest = df.drop_duplicates(subset=['name']).sort_values(by='duration_ms', ascending=False)
    return longest[['name', 'artist', 'duration_ms']].head(top_n)

if __name__ == "__main__":
    # Statistik rekomendasi
    print("\n=== 10 Lagu Top Trending (Terbaru) ===")
    print(top_trending_songs(df, 10).to_string(index=False))

    print("\n=== 10 Lagu Top Popular ===")
    print(top_popular_songs(df, 10).to_string(index=False))

    print("\n=== 10 Lagu Top Explicit ===")
    print(top_explicit_songs(df, 10).to_string(index=False))

    print("\n=== 10 Lagu Terpanjang Durasi ===")
    print(top_longest_duration(df, 10).to_string(index=False))

"""# Print Recommendations for All Users

Bagian ini bertujuan untuk menampilkan daftar rekomendasi lagu untuk setiap pengguna dalam rentang tertentu. Hal ini berguna untuk:

Memverifikasi hasil rekomendasi model untuk banyak pengguna sekaligus.

Memudahkan review dan presentasi hasil rekomendasi.

Menunjukkan variasi rekomendasi sesuai preferensi tiap pengguna.

# Rekomendasi lagu untuk user
"""

# 13. Print Recommendations for All Users
# Baca data lagu dari CSV
df_songs = pd.read_csv('spotify_cris_music1.csv')
song_list = df_songs['name'].tolist()

def predict_score(user_id, song):
    # Dummy prediksi (ganti dengan model asli)
    return random.random()

def recommend_songs(user_id, top_n=5):
    all_songs = list(song_list)
    scores = []
    for song in all_songs:
        score = predict_score(user_id, song)
        scores.append((song, score))
    scores.sort(key=lambda x: x[1], reverse=True)
    top_candidates = scores[:20]
    recommendations = random.sample(top_candidates, min(top_n, len(top_candidates)))
    recommended_songs = [song for song, score in recommendations]
    return recommended_songs

def recommend_for_all_users(start=1, end=200, top_n=5):
    print(f"=== Rekomendasi Musik untuk User {start} sampai {end} ===\n")
    for user_id in range(start, end + 1):
        recs = recommend_songs(user_id, top_n=top_n)
        print(f"User {user_id} rekomendasi lagu:")
        for i, song in enumerate(recs, 1):
            print(f"  {i}. {song}")
        print()

if __name__ == "__main__":
    recommend_for_all_users()